name: CICD-sample

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    cicd-sample:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: read

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: "schema-consumer/.nvmrc"
                  registry-url: "https://npm.pkg.github.com"

            - name: Install and run
              working-directory: ./schema-consumer
              run: |
                  npm install
                  npx tsx src/main.ts
              env:
                  GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}
